### ISSUE TITLE
Cetak stiker

### ISSUE THREAD

**Issue by herpiko** [LombokDevMeetup/lombokdevmeetup.github.io#1]

**Comment by herpiko** [comment]
Stiker otw cetak. 
![screenshot_2017-09-30_03-24-19](https://user-images.githubusercontent.com/2534060/31034589-e95d2ce2-a58e-11e7-8386-b1245655b27c.png)

**Comment by ardianta** [comment]
cetak di mana itu @herpiko?

**Comment by herpiko** [comment]
Custom.co.id

**Comment by herpiko** [comment]
![stiker-ldm](https://user-images.githubusercontent.com/2534060/31558939-1498e5b4-b079-11e7-94c0-5326055e819c.jpg)
