### ISSUE TITLE
Susunan acara

### ISSUE THREAD

**Issue by herpiko** [LombokDevMeetup/lombokdevmeetup.github.io#2]
Mohon dijabarkan, dari jam berapa sampai jam berapa, urutannya giman, dan isinya gimana.

**Comment by Cepul** [comment]
09.00-09.30 > persiapan acara
09.30-10.00 > daftar ulang peserta
10.00-10.30 > materi pertama + tanya jawab
10.30-11.00 > materi kedua + tanya jawab
11.00-11.30 > materi ketiga + tanya jawab
11.30-12.00 > materi keempat + tanya jawab
12.00-13.00 > istirahat
13.00-13.30 > materi kelima + tanya jawab
13.30-14.00 > materi keenam + tanya jawab
14.30-15.00 > materi ketujuh + tanya jawab
15.00-16.00 > istirahat
16.00-17.00 > diskusi bersama

**Comment by Cepul** [comment]
09.00-09.30 > persiapan acara
09.30-10.00 > daftar ulang peserta
10.00-10.20 > materi pertama + tanya jawab
10.20-10.40 > materi kedua + tanya jawab
10.40-11.00 > materi ketiga + tanya jawab
11.00-11.20 > materi keempat + tanya jawab
11.20-11.40 > materi kelima + tanya jawab
11.40-12.00 >materi keenam + tanya jawab
12.00-13.00 > istirahat
13.00-13.20 > materi ketujuh + tanya jawab
13.20-13.40 > materi kedelapan + tanya jawab
13.40-14.00 > materi kesembilan + tanya jawab
14.00-14.20 > materi kesepuluh + tanya jawab
14.20-14.40 > materi kesebelas + tanya jawab
14.40-15.00 > materi kedua belas + tanya jawab
15.00-16.00 > istirahat
16.00-17.00 > diskusi bersama

**Comment by Cepul** [comment]
nanti kalau sudah fix materi dan pembicara serta urutannya kabarin di sini, biar saya rapikan

**Comment by herpiko** [comment]
github.com/lombokdevmeetup/meetup/blob/master/001/acara.md
