### ISSUE TITLE
Persiapan fasilitas (soundsystem, etc)

### ISSUE THREAD

**Issue by herpiko** [LombokDevMeetup/lombokdevmeetup.github.io#3]
- Sound system
- LCD

**Comment by Ivanhadi** [comment]
saya juga biasa siapakan lokasi sama sound, LCD full. insha allah.....

**Comment by herpiko** [comment]
@Ivanhadi , mantap, saya tulisin detilnya di deskripsi

**Comment by Ivanhadi** [comment]
ok...kalau bisa ada yang temenin  juga dari lombok di grup biar bisa komunikasi nanti.

**Comment by herpiko** [comment]
Di Sucipto sudah tersedia : 
- 1 proyektor
- 1 layar proyektor
- Soundsystem dengan 2 mic (1 wire & 1 wireless)
- kursi-kursi dan sofa untuk banyak orang

Jika dapat VGA splitter dan kabel VGA yang cukup panjang, pakai proyektor dan layar tambahan darn pak Sapto Sutardi.

**Comment by KhaerulAnwar** [comment]
Maaf Saya masih bingung.,.,
untuk menjalankan file yg di github ini pakek apa ya /

**Comment by herpiko** [comment]
@KhaerulAnwar Sesuai dengan repository masing-masing, mestinya ada dokumentasi yang menjelaskan isi dari repo tersebut isinya apa. Jika tidak ada, silakan membuat `issue` di repo terkait.
