### ISSUE TITLE
Persiapan koordinasi tempat acara

### ISSUE THREAD

**Issue by herpiko** [LombokDevMeetup/lombokdevmeetup.github.io#4]
Minimal : 
- Lokasi Mataram
- Nyaman (misalnya ada AC)
- Muat kurleb 50 orang
- Ada bidang polos untuk LCD proyektor

**Comment by Ivanhadi** [comment]
Ivan

**Comment by Ivanhadi** [comment]
insha allah ada semua,, sound, lcd, ac, wifi, cuman belum cek apakah ada kursi mejax -_-

**Comment by khyrulimam** [comment]
lesehan tak apa..

**Comment by Ivanhadi** [comment]
kalau lesehan berarti sudah fix dah. tinggal ngelobi aja nanti.
semoga tanggal itu tidak di pakai aula dikporax...

**Comment by khyrulimam** [comment]
FYI.. @herpiko gak bisa baca EYTD.. :laughing:

**Comment by herpiko** [comment]
@khyrulimam Mmmm, saya ngelap kacamata dulu.

**Comment by herpiko** [comment]
ITEC bisa jadi alternatif kalau Dikpora gagal. Maks 30 orang. Mas Wahyu sudah konfirmasi dukung.

**Comment by herpiko** [comment]
Positif disponsori ITEC, 40 RSVP, pembicara sama panitia bisa nyempil di ruangan sebelah.

**Comment by herpiko** [comment]
Peserta pendaftar sudah mencapai 95 orang. Sedang diusahakan pindah tempat.

**Comment by herpiko** [comment]
Sponsorship ITEC diganti coffee break.

**Comment by herpiko** [comment]
Pindah ke https://goo.gl/maps/2QdLZCztL842
